=== rodriguesismael/ProjetoLES/EstacionamentoBasanela/build/web/CONFIG-INF/framework-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : framework-config.dtd
      Created on : 1 de Novembro de 2007, 12:30
    Author     : Matheus Ferrari
    Description:
        Purpose of the document follows.

-->

<!ELEMENT config (logics)>
<!ELEMENT logics (logic+)>
<!ELEMENT logic  ANY>
<!ATTLIST logic name ID #REQUIRED>
<!ATTLIST logic typeRequest ID #REQUIRED>
<!ATTLIST logic type CDATA #REQUIRED>

=== rodriguesismael/ProjetoLES/EstacionamentoBasanela/web/CONFIG-INF/framework-configCI.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : framework-config.xml
    Created on : 1 de Novembro de 2007, 12:30
    Author     : Matheus Ferrari
    Description:
        Purpose of the document follows.
-->
<!DOCTYPE config SYSTEM "framework-config.dtd">
<config>
    <logics>
        <!-- Veiculo -->
        <logic name="FormCadVeiculoAvulso" type="negocio.veiculo.FormCadVeiculoAvulso"></logic>
        <logic name="FormCadVeiculoMensal" type="negocio.veiculo.FormCadVeiculoMensal"></logic>
        <logic name="ListarVeiculo" type="negocio.veiculo.ListarVeiculo"></logic>
        <logic name="FormAltVeiculo" type="negocio.veiculo.FormAltVeiculo"></logic>
        <logic name="AlterarVeiculo" type="negocio.veiculo.AlterarVeiculo"></logic>
        <!-- Outro -->
        <logic name="FormHome" type="negocio.outro.FormHome"></logic>
        <logic name="EfetuarLogoff" type="negocio.outro.EfetuarLogoff"></logic>
        <!-- Movimento -->
        <logic name="RegistrarEntrada" type="negocio.movimento.RegistrarEntrada"></logic>
        <logic name="RegistrarSaida" type="negocio.movimento.RegistrarSaida"></logic>
        <!-- Cliente-->
        <logic name="FormCadCliente" type="negocio.cliente.FormCadCliente"></logic>
        <logic name="ListarCliente" type="negocio.cliente.ListarCliente"></logic>
        <logic name="FormAltCliente" type="negocio.cliente.FormAltCliente"></logic>
        <logic name="AlterarCliente" type="negocio.cliente.AlterarCliente"></logic>
        <logic name="AtivarCliente" type="negocio.cliente.AtivarCliente"></logic>
        <logic name="InativarCliente" type="negocio.cliente.InativarCliente"></logic>
        <!-- Operador -->
        <logic name="ListarOperador" type="negocio.operador.ListarOperador"></logic>
        <logic name="FormCadOperador" type="negocio.operador.FormCadOperador"></logic>
        <logic name="FormAltOperador" type="negocio.operador.FormAltOperador"></logic>
        <logic name="CadastrarOperador" type="negocio.operador.CadastrarOperador"></logic>
        <logic name="AtivarOperador" type="negocio.operador.AtivarOperador"></logic>
        <logic name="InativarOperador" type="negocio.operador.InativarOperador"></logic>
        <logic name="AlterarOperador" type="negocio.operador.AlterarOperador"></logic>
    </logics>
</config>

=== rodriguesismael/ProjetoLES/EstacionamentoBasanela/build/web/CONFIG-INF/framework-configUI.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : framework-config.xml
    Created on : 1 de Novembro de 2007, 12:30
    Author     : Matheus Ferrari
    Description:
        Purpose of the document follows.
-->
<!DOCTYPE config SYSTEM "framework-config.dtd">
<config>
    <logics>
        <!-- Login -->
        <logic name="EfetuarLogin" type="negocio.outro.EfetuarLogin"></logic>
        <!-- Veiculo -->
        <logic name="BuscarVeiculo" type="negocio.veiculo.BuscarVeiculo"></logic>
        <logic name="CadastrarVeiculo" type="negocio.veiculo.CadastrarVeiculo"></logic>
        <!-- Modelo -->
        <logic name="BuscarModelo" type="negocio.modelo.BuscarModelo"></logic>
        
        <!-- Cliente-->
        <logic name="BuscarCliente" type="negocio.cliente.BuscarCliente"></logic>
        <logic name="CadastrarCliente" type="negocio.cliente.CadastrarCliente"></logic>
        
        <!-- Cidade-->
        <logic name="BuscarCidade" type="negocio.cidade.BuscarCidade"></logic>        

    </logics>
</config>
